name: ci

on:
  push:
    branches: [ master ]

jobs:
  setup:
    name: "Checkout & Changelog"
    runs-on: self-hosted

    outputs:
      clean_changelog: ${{ steps.changelog.outputs.clean_changelog }}
      tag: ${{ steps.changelog.outputs.tag }}
      skipped: ${{ steps.changelog.outputs.skipped }}

    steps:
      - uses: actions/checkout@v3

      - name: Generate Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          git-message: 'chore(release): {version}'
          release-count: 0

  build:
    name: "Build & Generate"
    needs: [ setup ]
    runs-on: self-hosted

    steps:
      - name: Setup Nodejs and npm
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: npm

      - name: Setup yarn
        run: npm install -g yarn

      - name: Setup Nodejs with yarn caching
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Generate
        run: yarn generate
